Imported 2.765
No reason for CPC update specified.

diff --git a/live-build/auto/config b/live-build/auto/config
--- a/live-build/auto/config
+++ b/live-build/auto/config
@@ -1,7 +1,14 @@
 #! /bin/sh
 set -e
 
-rm -rf config
+if [ -e config/germinate-output ]; then
+            mv -T config/germinate-output germ-tmp
+            rm -rf config
+            mkdir config
+            mv -T germ-tmp config/germinate-output
+else
+        rm -rf config
+fi
 
 echo "Building on $(hostname --fqdn)"
 
@@ -298,7 +305,7 @@ _sanitize_passes ()
 		# if root pass, no parent to find
 		[ -z "$parent" ] && continue
 		if [ $(echo "$passes"|grep -cE "^$parent\$") -ne 1 ]; then
-			echo "ERROR: '$parent' is required by '$pass' but is missing. Registered passes are:\n$passes"
+			echo "ERROR: '$parent' is required by '$pass' but is missing. Registered passes are:\n$passes" >&2
 			exit 1
 		fi
 	done
@@ -867,6 +874,18 @@ case $PROJECT in
 					add_package ubuntu-server-minimal.ubuntu-server.installer.$flavor $kernel_metapkg
 					LIVE_PASSES="${LIVE_PASSES:+$LIVE_PASSES }ubuntu-server-minimal.ubuntu-server.installer.$flavor"
 				done
+				case $ARCH in
+					amd64)
+						add_package ubuntu-server-minimal.ubuntu-server.installer.generic.netboot grub-pc shim-signed pxelinux
+						;;
+					arm64)
+						add_package ubuntu-server-minimal.ubuntu-server.installer.generic.netboot shim-signed
+						;;
+					*)
+						add_package ubuntu-server-minimal.ubuntu-server.installer.generic.netboot
+						;;
+				esac
+				NO_SQUASHFS_PASSES=ubuntu-server-minimal.ubuntu-server.installer.generic.netboot
 
 				/usr/share/livecd-rootfs/checkout-translations-branch \
 					https://git.launchpad.net/subiquity po config/catalog-translations
