Imported 24.04.21 from noble-release pocket.
No reason for CPC update specified.

diff --git a/live-build/auto/config b/live-build/auto/config
--- a/live-build/auto/config
+++ b/live-build/auto/config
@@ -107,6 +107,31 @@ _register_pass () {
 	# $1 Name of the pass
 	[ "$PASSES_TO_LAYERS" != "true" ] && return
 
+	case "$PASSES" in
+		*$1*)
+			# The pass is already registered in the list of layers.
+			# If PASSES_TO_LAYERS is true, then the above if statement's error
+			# code will be non-zero and a return statement with no argument
+			# will return the error code of the if statement, non-zero, thus
+			# exiting the script and build. This is not our intent. So we need
+			# to return 0 here.
+			return 0
+			;;
+	esac
+
+	# live-build/ubuntu/hooks/020-ubuntu-live.chroot_early assumes the
+	# layer ending in '.live' is THE live layer to use, so ensure that
+	# we only define a single layer ending in '.live'.  It principle it
+	# is not invalid to have multiple layers with .live in the name but
+	# we should not let this happen accidentally.
+	case "$PASSES $1" in
+		*.live\ *.live)
+			echo "ERROR: only one 'live' layer allowed"
+			exit 1
+			;;
+		*)
+			;;
+	esac
 	PASSES="$PASSES $1"
 }
 
