Imported 2.600
No reason for CPC update specified.

diff --git a/live-build/functions b/live-build/functions
--- a/live-build/functions
+++ b/live-build/functions
@@ -483,11 +483,19 @@ _snap_preseed() {
             ;;
         *)
             # Determine if and what core snap is needed
-            local core_snap=$(/usr/share/livecd-rootfs/snap-tool info \
+            local snap_info
+
+            snap_info=$(/usr/share/livecd-rootfs/snap-tool info \
                 --cohort-key="${COHORT_KEY:-}" \
-                --channel="$CHANNEL" "$SNAP_NAME" | \
-                grep '^base:' | awk '{print $2}'
+                --channel="$CHANNEL" "${SNAP_NAME}" \
             )
+
+            if [ $? -ne 0 ]; then
+                echo "Failed to retrieve base of $SNAP_NAME!"
+                exit 1
+            fi
+
+            local core_snap=$(echo "$snap_info" | grep '^base:' | awk '{print $2}')
 
             # If $core_snap is not the empty string then SNAP itself is not a core
             # snap and we must additionally seed the core snap.
@@ -611,6 +619,12 @@ snap_prepare() {
     local CUSTOM_BRAND_MODEL=${2:-generic:generic-classic}
 
     snap_prepare_assertions "$CHROOT_ROOT" "$CUSTOM_BRAND_MODEL"
+
+    # ubuntu-cpc:minimized has its own special snap handling
+    if [ "$PROJECT:${SUBPROJECT:-}" != ubuntu-cpc:minimized ]; then
+        # Download the core snap
+        _snap_preseed "$CHROOT_ROOT" core stable
+    fi
 }
 
 snap_preseed() {
